### ISSUE TITLE
Would it be better to base this Dockerfile on something other than Ubuntu:trusty?

### ISSUE THREAD

**Issue by paimpozhil** [progrium/nginx-appliance#1]
I mean since this is a specific nginx appliance 

does it help to use a more minimal OS image than the ubuntu? 

Do you think the advantage of having slimmer images outweigh the convenience of running ubuntu image with APT ?

**Comment by bacongobbler** [comment]
looks like this can be closed out now :)

**Comment by josegonzalez** [comment]
^ bump on closing :)
